"""add book_embeddings table

Revision ID: d9bd3af3bfa4
Revises: 80e3554715b7
Create Date: 2026-06-02 17:01:56.334058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9bd3af3bfa4'
down_revision: Union[str, Sequence[str], None] = '80e3554715b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add book_embeddings table.

    Stores one 384-dimensional vector per book, plus the model name that
    produced it and a timestamp. PK is book_id alone — single model per book
    for v1; future multi-model support would need a schema bump.

    The IVFFlat index is NOT created here. pgvector requires the table to
    contain data when the index is built so centroids can be clustered
    correctly. The index is created at the end of generate_embeddings.py
    after vectors are inserted.

    Dimension is locked to 384 to match BAAI/bge-small-en-v1.5. Switching to
    a 768-dim model (e.g. all-mpnet-base-v2) requires a new migration that
    alters or recreates the embedding column.
    """
    op.execute("""
        CREATE TABLE book_embeddings (
            book_id    UUID PRIMARY KEY REFERENCES books(id) ON DELETE CASCADE,
            embedding  VECTOR(384) NOT NULL,
            model      VARCHAR(128) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)


def downgrade() -> None:
    """Drop book_embeddings table.

    The books table is unaffected. Embeddings can be regenerated by
    re-running scripts/generate_embeddings.py.
    """
    op.execute("DROP TABLE IF EXISTS book_embeddings")
