"""add concept_embeddings table

Revision ID: fbad272ac42a
Revises: d9bd3af3bfa4
Create Date: 2026-06-06 12:51:28.346327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbad272ac42a'
down_revision: Union[str, Sequence[str], None] = 'd9bd3af3bfa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add concept_embeddings table.

    One 384-dim vector per concept (56 rows total). Used by
    gap_query_embedding service to find books semantically similar to
    the user's top gap concepts, bypassing the annotation-density
    constraint on gap scoring.

    PK is concept_id alone — single model per concept for v1; future
    multi-model support would need a schema bump.

    No IVFFlat index. With only 56 rows, brute-force sequential scan
    is faster than approximate nearest-neighbor lookup. Revisit if
    the taxonomy ever grows past several hundred concepts.

    Dimension is 384 to match BAAI/bge-small-en-v1.5 (the same model
    used for book_embeddings). Switching to a 768-dim model requires
    a new migration that alters or recreates the embedding column.
    """
    op.execute("""
        CREATE TABLE concept_embeddings (
            concept_id UUID PRIMARY KEY REFERENCES concepts(id) ON DELETE CASCADE,
            embedding  VECTOR(384) NOT NULL,
            model      VARCHAR(128) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)


def downgrade() -> None:
    """Drop concept_embeddings table.

    The concepts table is unaffected. Embeddings can be regenerated by
    re-running scripts/generate_concept_embeddings.py.
    """
    op.execute("DROP TABLE IF EXISTS concept_embeddings")
